# Generated by Django 4.0.4 on 2022-04-11 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cname',
            new_name='name',
        ),
    ]
