# Generated by Django 4.0.4 on 2022-04-11 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_rename_cname_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='publication_date',
        ),
        migrations.RenameField(
            model_name='subforum',
            old_name='post_qty',
            new_name='posts',
        ),
    ]
