# Generated by Django 4.0.4 on 2022-04-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_post_subforum_remove_subforum_posts_thread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subforum',
            name='path',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
