# Generated by Django 4.0.4 on 2022-04-13 19:59
# Edited to mess with slug fields

from django.db import migrations, models
from django.utils.text import slugify

def populateThreadSlugFields(apps, schema_editor):
    thread = apps.get_model('forum', 'Thread')
    for row in thread.objects.all():
        row.slug = slugify(row.title)
        row.save()

def populateSubforumSlugFields(apps, schema_editor):
    subforum = apps.get_model('forum', 'Subforum')
    for row in subforum.objects.all():
        row.path = slugify(row.title)
        row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_subforum_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default='Default'),
            preserve_default=False,
        ),
        migrations.RunPython(populateThreadSlugFields, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='subforum',
            name='path',
            field=models.SlugField(null=True),
        ),
        migrations.RunPython(populateSubforumSlugFields, reverse_code=migrations.RunPython.noop),
    ]
