# Generated by Django 4.0.3 on 2022-04-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_thread_slug_alter_subforum_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
