# Generated by Django 4.0.4 on 2022-04-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_alter_post_thread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='reply',
            new_name='repliesTo',
        ),
    ]
