# Generated by Django 4.0.4 on 2022-04-17 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_rename_reply_post_repliesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='repliesTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.post'),
        ),
    ]
